services:

  aggregator:
    build: ./aggregator-service
    ports:
      - "8000:8000"
    environment:
      - AUTH_URL=http://auth:8000

  hospital1:
    build: ./hospital-node
    ports:
      - "8001:8000"

  hospital2:
    build: ./hospital-node
    ports:
      - "8002:8000"
  auth:
    build: ./auth-service # Build from Dockerfile in this folder
    ports:
      - "8003:8000" # laptop:8000 → container:8000
    networks: [ medfl-net ]
    environment:
      REDIS_URL: redis://redis:6379 # env var passed into the container
    volumes:
      - ./auth-service/certs:/app/certs

  redis:
    image: redis:7-alpine # Pull this image from Docker Hub
    networks: [ medfl-net ]
  storage:
    build: ./model-storage-service
    ports:
      - "8004:8000"

  monitor:
    build: ./monitoring-service
    ports:
      - "8005:8000"

networks:
  medfl-net:
