# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fl_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66l_service.proto\x12\x05medfl\"2\n\x0cModelRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"w\n\rModelResponse\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\x10\n\x08round_id\x18\x02 \x01(\x05\x12\x11\n\tn_classes\x18\x03 \x01(\x05\x12\x11\n\tencrypted\x18\x04 \x01(\x08\x12\x11\n\talgorithm\x18\x05 \x01(\t\x12\n\n\x02mu\x18\x06 \x01(\x02\"\xb5\x01\n\rUpdateRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08round_id\x18\x03 \x01(\x05\x12\x14\n\x0cweight_delta\x18\x04 \x01(\x0c\x12\x12\n\nlabel_dist\x18\x05 \x03(\x02\x12\x11\n\tn_samples\x18\x06 \x01(\x05\x12\x11\n\tencrypted\x18\x07 \x01(\x08\x12\x10\n\x08\x61\x63\x63uracy\x18\x08 \x01(\x02\x12\x0c\n\x04loss\x18\t \x01(\x02\".\n\tUpdateAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0bPingRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\"\x1e\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb1\x01\n\tFLService\x12;\n\x0eGetGlobalModel\x12\x13.medfl.ModelRequest\x1a\x14.medfl.ModelResponse\x12\x36\n\x0cSubmitUpdate\x12\x14.medfl.UpdateRequest\x1a\x10.medfl.UpdateAck\x12/\n\x04Ping\x12\x12.medfl.PingRequest\x1a\x13.medfl.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELREQUEST']._serialized_start=27
  _globals['_MODELREQUEST']._serialized_end=77
  _globals['_MODELRESPONSE']._serialized_start=79
  _globals['_MODELRESPONSE']._serialized_end=198
  _globals['_UPDATEREQUEST']._serialized_start=201
  _globals['_UPDATEREQUEST']._serialized_end=382
  _globals['_UPDATEACK']._serialized_start=384
  _globals['_UPDATEACK']._serialized_end=430
  _globals['_PINGREQUEST']._serialized_start=432
  _globals['_PINGREQUEST']._serialized_end=466
  _globals['_PINGRESPONSE']._serialized_start=468
  _globals['_PINGRESPONSE']._serialized_end=498
  _globals['_FLSERVICE']._serialized_start=501
  _globals['_FLSERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
