FROM python:3.10

WORKDIR /dashboard

COPY dashboard_requirements.txt .
RUN pip install -r dashboard_requirements.txt

COPY dashboard.py .

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
